on:
  push:
    branches:
      - live
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: create env file
        run: |
          touch .env
          echo VITE_API_URL=${{ secrets.VITE_API_URL }} >> .env

      - name: Install packages
        run: npm install

      - name: Generate Nuxt static files
        run: npm run build

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist s3://imagine-apps.com --delete
